/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Money:": "金钱:",
    "Load Game": "加载游戏",
    "SKILLS": "技能",
    "skills": "技能",
    "STORY": "故事",
    "story": "故事",
    "status": "状态",
    "STATUS": "状态",
    "Music": "音乐",
    "LEVEL": "等级",
    "STR": "力量",
    "STR:": "力量:",
    "Throwing Knife": "飞刀",
    "The Void": "虚空",
    "Streets": "街头",
    "strength": "力量",
    "Strength": "力量",
    "TRAINING": "训练",
    "training": "训练",
    "Upgrade:": "升级:",
    "Reset": "重置",
    "Requires:": "要求:",
    "Save Game": "保存游戏",
    "Max health:": "最大生命值：",
    "Jab": "工作",
    "HELP": "帮助",
    "HEALTH": "生命值",
    "human": "人",
    "Next move:": "下一步行动:",
    "abilities": "能力",
    "ABILITIES": "能力",
    "\\/ SCROLL DOWN \\/": "\\/ 向下滚动 \\/",
    "AREAS": "区域",
    "areas": "区域",
    "Bridge": "桥梁",
    "Crowbar": "撬棍",
    "Currently training:": "当前训练：",
    "Strength:": "力量:",
    "(Arrow keys or scroll down to 'Training').": "（箭头键或向下滚动到“培训”）。",
    "Agility": "敏捷",
    "Agility:": "敏捷:",
    "All that training has made you swole. That first hit really packs a punch": "所有的训练都让你气喘吁吁。 第一击真的很有冲击力",
    "Alley": "胡同",
    "And a cold one after work.": "下班后又感冒了。",
    "Attributes:": "属性:",
    "Class:": "类别:",
    "Coach said this would toughen you up.": "教练说这会让你变得坚强。",
    "Diary": "日记",
    "Firecackers": "鞭炮",
    "Haymaker": "干草机",
    "Health regeneration: health regeneration per second in combat.": "生命恢复：战斗中每秒生命恢复。",
    "It's funnier in the circus": "马戏团里更有趣",
    "It's just like hard candy.": "就像硬糖一样。",
    "Jays on my feet.": "松鸦在我脚上。",
    "Let's say, hypothetically....": "比方说，假设......",
    "MND": "头脑",
    "Mind": "头脑",
    "Mind:": "头脑:",
    "MND:": "头脑:",
    "Training (": "训练 (",
    "Park": "公园",
    "Underground Lab": "地下实验室",
    "Upgrade available!": "可升级！",
    "walk": "走路",
    "We used to do this as kids.": "我们小时候经常这样做。",
    "This does not seem fair?": "这似乎不公平？",
    "They weren't using them anyways.": "反正他们也没用。",
    "Toughness": "坚韧",
    "Toughness:": "坚韧:",
    "With all the beatings you've taken and lived through, it takes a lot to bring you down.": "你经历了那么多的打击，要让你崩溃是很困难的。",
    "You're more likely to blow off your own fingers than theirs.": "你更有可能炸飞自己的手指，而不是他们的。",
    "Your browser does not support the audio element.": "您的浏览器不支持音频元素。",
    "Your first move is Punch. Punch's damage ratio is 80%": "你的第一步就是出拳。重击的伤害比是80%",
    "Your hero automatically uses his skills in combat.": "你的英雄会自动在战斗中使用他的技能。",
    "Faster than a punch but weaker, good to knockout small fry and get out of the way.": "比一拳更快，但更弱，很好地击倒小鱼苗并让开。",
    "criticalChance": "暴击率",
    "Critical strike: chance to deal 50% more damage.": "致命一击：造成额外 50% 伤害的几率。",
    "Check it, mate, I won.": "看看吧，伙计，我赢了。",
    "Being faster than your foe gives you the opportunity to hit them in a vital spot.": "比你的敌人更快让你有机会击中他们的要害点。",
    "Base attributes from training": "来自训练的基本属性",
    "Attributes per session:": "每个会话的属性：",
    "Attributes can be increased by training.": "属性可以通过训练增加。",
    "AGI": "敏捷",
    "AGI:": "敏捷:",
    "Actually learn it. Don't memorize it.": "实际上学习它。 不要死记硬背。",
    "Active abilities:": "主动能力：",
    "A simple punch, everyone knows how to do it.": "简单的一拳，谁都会。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Use time: ": "用时：",
    "Range: ": "距离：",
    "Cooldown: ": "冷却: ",
    "\"Big Boy Pills\" ": "\"大童丸\" ",
    "\"Borrowed Dumbells\" ": "\"借来的哑铃\" ",
    "Attend debate club": "参加辩论俱乐部",
    "Construction Job": "建筑工作",
    "Damage range: ": "伤害距离: ",
    "Training at: ": "训练地点：",
    "Win at street chess": "在街头象棋中获胜",
    "Get to": "得到",
    "Five Mile Run": "五英里跑",
    "Dodge the swing": "躲开秋千",
    "Built To Last": "经久耐用",
    "Calisthenics": "健美操",
    "Acquire J's": "收购J的",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^伤害距离(.+)$/,
    /^用时(.+)$/,
    /^范围(.+)$/,
    /^冷却(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)s$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^LEVEL ([\d\.,]+)$/, '等级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) Points$/, '成本：$1 点数'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);